name: Build and deploy Node.js app to Azure Web App - erp-backend

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: server   # 👈 all commands run inside server/

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server   # 👈 package server folder, not the entire repo

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'erp-backend'
          slot-name: 'Production'
          package: .   # 👈 will now point to the unpacked server artifact
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
